name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clang
        run: sudo apt-get install -y clang

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ 

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Package application
        run: |
          mkdir -p package
          cp -r build/* package/
          tar -czf snake-game.tar.gz -C package .

      - name: Create DEB package
        run: |
          mkdir -p package/DEBIAN
          echo "Package: snake-game" > package/DEBIAN/control
          echo "Version: 1.0" >> package/DEBIAN/control
          echo "Section: games" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: amd64" >> package/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> package/DEBIAN/control
          echo "Description: Snake game" >> package/DEBIAN/control
          mkdir -p package/usr/local/bin
          cp build/snake-game package/usr/local/bin/
          dpkg-deb --build package snake-game.deb