name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clang
        run: sudo apt-get install -y clang

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ 

      - name: Install SFML
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Verify Build Output
        run: |
          ls build
          if [ ! -f build/snake-game ]; then
            echo "Error: Executable not found!"
            exit 1
          fi

      - name: Package application
        run: |
          mkdir -p package
          cp -r build/* package/
          tar -czf snake-game.tar.gz -C package .

      - name: Create DEB package
        run: |
          mkdir -p package/DEBIAN
          echo "Package: snake-game" > package/DEBIAN/control
          echo "Version: 1.0" >> package/DEBIAN/control
          echo "Section: games" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: amd64" >> package/DEBIAN/control
          echo "Maintainer: kirill <kirya.sherstyuk.05@mail.ru>" >> package/DEBIAN/control
          echo "Description: Snake game" >> package/DEBIAN/control
          mkdir -p package/usr/local/bin
          cp build/snake-game package/usr/local/bin/
          dpkg-deb --build package snake-game.deb

      - name: Move DEB to release
        run: |
          mkdir -p release
          mv snake-game.deb release/
